### ISSUE TITLE
Removes spaces after a comma in json string value

### ISSUE THREAD

**Issue by Sushil231088** [fedeghe/malta-json-minify#1]
I noticed that the plugin removes spaces inside the string as well. Can you please fix?

Example:
`    {
         "text": "Traditional, Roth, Minor Roth, Rollover"
     },
`

Output:
`
{"text":"Traditional,Roth,Minor Roth,Rollover"}
`

**Comment by fedeghe** [comment]
Thank You! I’m going to fix it really soon

**Comment by fedeghe** [comment]
solved in version 1.0.4
